# Generated by Django 5.2.6 on 2025-09-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fronend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('img', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
                ('type', models.CharField(choices=[('simple', 'Simple'), ('premium', 'Premium')], default='simple', max_length=10, verbose_name='Turi')),
                ('tavsif', models.TextField(verbose_name='Tavsifi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
